### ISSUE TITLE
Bot does not send messages back to discord

### ISSUE THREAD

**Issue by tsukari** [reactiflux/discord-irc#111]
Starting about 12 hours ago the  bot could no longer send messages it receives from irc  to discord, we have the latest version but can't seem to figure out whats blocking it.

**Comment by hewball** [comment]
+1 having this issue too

**Comment by ssatanss** [comment]
+1

**Comment by altyr** [comment]
Apparently a fix was released (see #110 ), but it hasn't resolved this problem for me.

**Comment by Scuba95** [comment]
The fix in the new patch doesn't work for me, either.

**Comment by altyr** [comment]
It appears that a specific version of discord.js fixes the problem. Running
`npm uninstall discord.js`
` npm install hydrabolt/discord.js#indev-old`
fixed things for me. (found on the bot-development discord server)

**Comment by atb26** [comment]
Thank you @altyr - that fixed the problem for me, also

**Comment by ekmartin** [comment]
Hm, that's weird. The issue was resolved for me with the latest patch. `#indev-old` adds a commit that does the same thing as the patch I added, by prefixing bot tokens with `Bot` if they aren't already. The latest version of discord.js is 9.1.0, while we're using 8.1.0. I'm a bit hesitant to upgrade, as it requires Node.js 6 and upwards (which means discord-irc would need to do the same).

**Comment by ekmartin** [comment]
Apparently there were a few more bug fixes in `#indev-old` that were needed. I've replaced my previous commit with a dependency change to that version of `discord.js`, so the issue should be resolved in the latest version of discord-irc now (`1.0.3`). Let me know if it isn't, and I'll reopen this.
