### ISSUE TITLE
Using discord-irc with TTS

### ISSUE THREAD

**Issue by TheBaconSpace** [reactiflux/discord-irc#135]
How Would i make This Do /tts on Discord For a Friend That has To use Text To speach To Hear

**Comment by ekmartin** [comment]
Hi @TheBaconSpace. It's nice of you to help your friend like this.
Do you want all messages from IRC to be sent as TTS commands?
If that's what you're after I made the [small changes](https://github.com/reactiflux/discord-irc/commit/d0631a30107baecba730403ef788acd41d0687bb) required in discord-irc to make this work, and pushed it to the `tts` branch. Here's how you can try it out:

1. Clone this repository with git, using `git clone https://github.com/reactiflux/discord-irc.git`
2. Navigate into the directory using `cd discord-irc`
3. Checkout the `tts` branch using `git checkout tts`
4. Install the npm dependencies using `npm install`
5. Build the project using `npm run build`
6. Start the project with `npm start -- --config config.json` where `config.json` is the name of the config file you've used previously (see the README for how this should look).

Feel free to PM me on Freenode (@ekmartin) or on Discord (ekmartin#5764) if you have any trouble with the steps :)

Note that this will read up the messages like "discord-irc says, ekmartin says hi", since the username of the bot is still discord-irc. This would be improved when #129 is implemented.

**Comment by ekmartin** [comment]
@dmodoomsirius made me realize that Discord already supports reading up all messages using TTS right out of the box, couldn't your friend use that instead?

User Settings -> Notifications -> Enable `For current selected channel`: 
![image](https://cloud.githubusercontent.com/assets/3536982/19225440/dbebb33a-8e6a-11e6-86fb-5cd9d897a07c.png)

**Comment by TheBaconSpace** [comment]
everything tts

**Comment by ekmartin** [comment]
Not sure I understand what you mean, care to elaborate?

**Comment by TheBaconSpace** [comment]
Wats ur Discord Tag so we Can Talk in Discord pm

**Comment by ekmartin** [comment]
ekmartin#5764

**Comment by TheBaconSpace** [comment]
sent

**Comment by TheBaconSpace** [comment]
[Nate](https://www.twitch.tv/natekh2) Started trying to do this So he Can do it and then i took over to help host it but we were having problems that i will tell u on discord

**Comment by TheBaconSpace** [comment]
Bacon_Space#1756
