### ISSUE TITLE
Support for multi-server channels

### ISSUE THREAD

**Issue by billimek** [reactiflux/discord-irc#15]
As a client, I want to be able to 'map' channels belonging to multiple different discord servers instead of a single discord server so that I can map across multiple discord servers per account.

**Comment by billimek** [comment]
For example:

```
[
  // Bot 1 (minimal configuration):
  {
    "nickname": "test2",
    "server": "irc.testbot.org",
    "discordEmail": "user@mail.com",
    "discordPassword": "letmein123",
    "channelMapping": {
      "discord_server #general": "#new-irc-channel" // add discord server name before discord server
      "discord_server2 #general": "#other-irc-channel" // add discord server name before discord server
    }
  }
]
```

**Comment by ekmartin** [comment]
With support for this I'm not sure if there's any point in having support for multiple bot users at all. It's there since this is really just a fork of https://github.com/ekmartin/slack-irc. Something like this wouldn't be possible with slack-irc, since it uses Slack's bot users (which don't authenticate like regular users, and are connected to one server). For Discord however I think what you're suggesting might be a better approach. 

One thing that's a bit negative is that it increases the gap between slack-irc and discord-irc. I've been thinking about ways to abstract away most of the modules' code into a general library, because it's kind of a pain to have so much duplicate code to maintain. However, that would definitely make it harder to have differences like what you're suggesting here (in addition to the existing differences), so I'm not sure if it's worth it.

I'm not sure if I'll have time implementing what you're suggesting in the close future though, so it's up for grabs if anyone wants to take a shot at it.

**Comment by billimek** [comment]
Submitted a pull request for this.
https://github.com/reactiflux/discord-irc/pull/18

**Comment by keenerb** [comment]
This is an important feature.  Please look into supporting multiple servers per user account; this is unusable for me right now because I have four servers linked to the same Discord account, and this is unable to connect to three of them.

**Comment by CallMeM** [comment]
I support this, but maybe not with this syntax, maybe a per server configuration alongside the default unique name config? Or maybe a way to alias a each server's channels to a new name? I don't know how possible the last one is, though.

**Comment by mcmonkey4eva** [comment]
Pinging in that I also could use this feature.

**Comment by demiters** [comment]
Yup. Want this also.

**Comment by Throne3d** [comment]
This seems to now be doable, using channel IDs? Where channel names are ambiguous, the bot will just end up using one or the other (which is obviously not the best behavior, but is hardly damaging), but if you use channel IDs (not ambiguous), it seems to work fine with two servers.

Like, if I have two discord servers:
```
test2
- #general2

test
- #general
- #chan2
```
And I have the following channel mapping:
```
"channelMapping": {
  "#general2": "#testbed",
  "#general": "#testbed2",
  "#chan2": "#testbed3"
}
```
As the channel names are not ambiguous, it works fine (even though `#general2` is on a different server from `#general` and `#chan2`).

Were `#general2` and `#general` named the same, so I have the following server structure:
```
test2
- #general (302121228901285888)

test
- #general (298833157329780736)
- #chan2
```
I could use the following mapping:
```
"channelMapping": {
  "302121228901285888": "#testbed",
  "298833157329780736": "#testbed2",
  "#chan2": "#testbed3"
}
```
Which, testing it quickly, seems to work as I'd expect?

(To get a channel ID, go to the server with the channel name, and into the chat bar write `\#channel`, e.g. `\#general` – this will get you something along the lines of `<#302121228901285888>`, which you can then extract the ID from.)

It's not quite so convenient as just specifying the server name and the channel to disambiguate, but it's functional.

**Comment by demiters** [comment]
@Throne3d I'm surprised that hasn't been clearly documented? Thanks anyway!

**Comment by Throne3d** [comment]
@demiters It was added in [v2.3.0](https://github.com/reactiflux/discord-irc/commit/cb184cc023dafd3b5f8e06b3c50a1e23e930d2f0), by way of PR #202. I guess it doesn't add documentation – I'll look into producing something satisfactory.
