### ISSUE TITLE
Bot able to connect on Windows but not on Linux

### ISSUE THREAD

**Issue by LeonellS** [reactiflux/discord-irc#227]
The bot is able to connect to Discord and the IRC channel fine when I host it locally but when I upload it to my friend's VPS, it is only able to connect to the IRC. The bot however appears as online but whenever a message is received on the IRC channel, it will print out the message "info: Tried to send a message to a channel the bot isn't in". 

Here is my config:
```
[
    {
        "nickname": "_redacted_",
        "server" : "_redacted_ipv6_",
        "discordToken" : "_redacted_",
        "channelMapping": {
            "_redacted_mapping_in_numerals_": "_irc_channel_and_key_"
        },
        "format": {
            "discord" : "<{$author}> {$withMentions}"
        },
        "ircNickColor": false,
        "ircOptions": {
            "debug": true,
            "showErrors": true,
            "autoRejoin": true,
            "autoReconnect": true
        }
    }
]
```
Any solutions?

**Comment by Throne3d** [comment]
Is there any other output in the console? Presumably nothing gets mirrored when things are said on the Discord side?

Does it definitely use the same token or are you using a different one on the VPS?

**Comment by LeonellS** [comment]
After awhile, there were 2 messages.
`error: Received error event from Discord message=uWs client connection error, stack=uWs client connection error`
`(node:15174) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Something took too long to do.`

Nothing gets mirrored back to the IRC channel whenever something was sent on Discord and yes, the token used on both sides are the same.

**Comment by Throne3d** [comment]
This doesn't sound like something we can easily help with, as it seems like the issue is somewhere between a library of ours, `discord.js`, and connecting to Discord itself.

Are you sure it appears as online, and that isn't just accidental from some other instance of the bot being run? (I mean, is it definitely connecting to Discord and setting the bot online, then just struggling with further things, or could it be that it's failing to connect at all…?)

If it could be failing to connect at all: are you sure you don't have a firewall enabled, the application is allowed to connect, you've not specified some bizarre config setting that gives a weird Discord port, the VPS has proper internet connectivity (including DNS and such)…?

**Comment by LeonellS** [comment]
I don't think it's failing to connect to Discord entirely since the bot does get shown as online when it is started on the VPS (No prior instances of the bot). However, sending messages from any of the channel including the one it is in doesn't really do anything (No error messages).
