### ISSUE TITLE
Massive memory usage

### ISSUE THREAD

**Issue by lrabe** [reactiflux/discord-irc#27]
discord-irc uses close to 140MB of RAM on my 512MB VPS.
There's only one channel mapping and not too much chatting going on.
Ubuntu version is 14.04.3 LTS, node version is 0.12.9

This is *way* to much.

Output of top: 

![discord-irc memory usage](http://qs.lc/erdj0) 

For my config.json, refer to #25

**Comment by ekmartin** [comment]
Sorry for the late answer. With a lot of event listeners it might just be that Node's garbage collector doesn't run before it really has to, i.e. thus the large memory usage. It doesn't seem like a memory leak, since it stabilizes instead of crashing. Could you try running the application with `--max_old_space_size` set to a low number? I think this should force garbage collection to run whenever it converges towards that memory usage, some discussion [here](https://github.com/nodejs/node/issues/2738).

I would also try upgrading to Node 5, as there apparently were several memory consumption improvements in Node 4. Upgrading on Ubuntu: https://github.com/nodesource/distributions#installation-instructions
