### ISSUE TITLE
Duplicate and frequently changing IRC nickname colors assigned to users

### ISSUE THREAD

**Issue by andersomoje** [reactiflux/discord-irc#275]
I am having an issue where several users from Discord will share the same color (always purple) for their IRC nickname. Although there are 5-8 people using the bridge, all of them save one or two will have the same color. Occasionally, they will suddenly have unique colors, but this never seems to last for more than a few minutes.

Steps to reproduce:
Have the IRC nickname color option enabled? Sorry I cannot be more helpful in this regard. I will attach some screenshots to better illustrate.

Expected Behavior: 
I would expect each user to be assigned a unique color code, and for these to remain assigned to each user for the remainder of their session. 

Environment: 
OS: linux
npm: 3.10.10
discord-irc: Current

Images:
![screenshot_2017-07-22_05-58-36](https://user-images.githubusercontent.com/30363744/28488860-80ca7706-6ea3-11e7-95e2-d4efd30741fe.png)

This image shows multiple users sharing the same color, despite there only being about 6 users.

![screenshot_2017-07-22_05-59-09](https://user-images.githubusercontent.com/30363744/28488862-86aa7270-6ea3-11e7-86ae-240d8b52f009.png)

This image shows multiple users suddenly receiving unique colors, and then returning to sharing the same color a few minutes later. Again, oddly, this behavior only affects users who are initially given purple.

Please let me know if any other information would be helpful.

**Comment by Throne3d** [comment]
The color is based off the first letter and length of the nickname. (Code is here: https://github.com/reactiflux/discord-irc/blob/7f7505cae7ebc1ee254792c04c2ec7f4ac55c143/lib/bot.js#L274)

It makes sense that `jan Kisi` would change color when becoming `janKisi`, since that's reduced in length, and also would make sense than `jan Kawa` and `jan Kisi` would be the same color (same initial letter, same length). I'm not however sure why `jan Kawa` would be a different color in the start of the second image. Which of those users (`^^^^`, `d__b`) is the `discord-irc` bot? Or are they both `discord-irc` bots?

**Comment by andersomoje** [comment]
Oh, thanks for the info on the first part, that makes a lot more sense.

^^^^ is teleirc, a bridge between IRC<>discord, and d__b is the discord-irc.

**Comment by Throne3d** [comment]
I don't think there's any unexpected behavior here, then? It looks like `d__b` is doing colors consistently with the behavior described.

(I personally wouldn't expect it to track users and then make decisions for how not to collide – that sounds like it would require weird heuristics and also the clients I've used which color nicknames don't handle it that way.)

**Comment by andersomoje** [comment]
Yep. I was unaware of the way that colors were handled, my apologies, nothing unexpected happening here.
