### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by theredmanor** [reactiflux/discord-irc#278]
Are you planning to support Windows in the future?

**Comment by mekolat** [comment]
nodejs is cross-platform

**Comment by Throne3d** [comment]
Technically it has trouble with `npm test` if you're not in a ~bash shell because of how it tries to find test files, but I expect that's not what's meant. (This should be relatively easily fixable.)

@theredmanor, you likely get errors when you install due to `iconv` and `node-icu-charset-detector`? These two dependencies are actually optional, and are I think required by the `irc-upd` (or `node-irc`) library.
