### ISSUE TITLE
Can I mapping multi IRC channel to one discord channel?

### ISSUE THREAD

**Issue by tsaijohn** [reactiflux/discord-irc#281]
My config is 

```
"channelMapping": {
        "#channel_name": "#irc_1",
        "--channelID--": "#irc_2"
}
```

The --channelID-- is the #channel_name's ID.
So that I can mapping both irc_1, irc_2 to the same channel.

but if I change my config to

```
"channelMapping": {
        "--channelID--": "#irc_1",
        "--channelID--": "#irc_2"
}
```

I can only see irc_2 in the channel.
Can I map more than 2 IRC channel to 1 discord channel?

**Comment by ekmartin** [comment]
No, a Javascript object can fundamentally only have unique keys, so your second channelID is overriding the first one. You might be able to get it working with two bots though, i.e. by passing an configuration array. Getting this to work otherwise would require changing the channel mapping completely, so I don't think that's worth it for an edgecase like this.

Happy to re-visit if more people disagree though.
