### ISSUE TITLE
Bot wont work at all.

### ISSUE THREAD

**Issue by ABlueLemon** [reactiflux/discord-irc#298]
So I have no idea what I am doing but here are all my files. I get no error messages when I run them, but they don't work. I don't even know what npm is. I already created a bot and added it to my server as well.

**Comment by Throne3d** [comment]
…Are you sure you don't get an error message?

For starters, you probably don't want to share your config without redacting the tokens. You also have double double-quotes around your token – that shouldn't be `""…token…""`, but should be `"…token…"`

`npm` is the program you use to run it. You run the commands in that file (without the dollar symbols – those represent that you can run them as a normal user instead of an administrative user). I'm not sure what `boot.npm` is?

**Edit**: You also need to put your password (inside the `"ircOptions"` object) inside quote marks. (And probably don't want to share it.)

**Comment by Kovaelin** [comment]
More details of how/where you're trying to deploy the bot would be helpful. Note that Google Cloud's free tier blocks sockets, so you won't be able to use it unless you pay. Also, you may need to use "sudo" before npm in some cases.
