### ISSUE TITLE
Feature Request: Allow connection of Discord bot to other Discord channels.

### ISSUE THREAD

**Issue by melt7777** [reactiflux/discord-irc#320]
- Currently we have a bot that maps 5 IRC channels to 5 Discord channels and it works perfectly.
- We also saw that in local [Issue #68](https://github.com/reactiflux/discord-irc/issues/68)  that there is a desire and a way to connect one Discord channel to two simultaneous IRC servers and channels. (Nice!!) 
- We would also like to be able to connect two discord channels across 2 networks without having to use an irc in the middle to bridge. Also, we have some webhooks/bots in the existing discord, which currently get lost in translation to IRC, so we would like to see if we can do Discord<->Discord directly. Preferably in the same discord-irc bot INSTANCE, but at least using the same code and a different conf would be a great second choice.
- Thank you very much!

**Comment by Throne3d** [comment]
I think this is out of scope for discord-irc, since it would need quite a bit of coercion of the current code to get it to allow discord-discord bridging (currently it's quite heavily set up to be just discord-irc, and so this would cause weird special-casing). There are probably bots out there for this, or failing that, it's probably quite straightforward to create one from the upstream discord.js library (if you have someone handy who's willing to code it for you)!
