### ISSUE TITLE
Crash caused by undefined value.

### ISSUE THREAD

**Issue by JJ173** [reactiflux/discord-irc#342]
So I'm using this for a Discord channel with around 2.5k users which is connected to a client which used IRC for chat based activity.

It transmits just fine as a bridge when it's working. However, occasionally I'm met with this error in my console and it's quite constant. 

![image](https://user-images.githubusercontent.com/17053495/34300905-40467246-e722-11e7-9633-125405f71bf8.png)

Is there anything I can try or do to stop this from appearing? Perhaps I've messed up on the install somewhere. Any ideas people? 

Thanks,
JJ

**Comment by JJ173** [comment]
Still suffering from this crash daily! Anyone?!

**Comment by Throne3d** [comment]
The log doesn't, I don't think, give enough information to figure out what's causing it or why. Looking in the codebase, I can't see anything (at least anything obvious) which tries to access `options` of _anything_, let alone something that might be nonexistent.

It might be a problem with an upstream library (but I think not the IRC one, since that also doesn't seem to make use of the `options` property on anything). I'm not sure. Are you definitely on the latest version of discord-irc (i.e. 2.5.0)? You can check this by looking at the output of `discord-irc --version`.

**Comment by Throne3d** [comment]
You may also be able to get more information by putting the bridge into debug mode – this can be done by running it with the environment variable `NODE_ENV=development` (ie prepending that to the command with a space, if you're on Linux or Mac in a standard shell), and putting `"debug": true` into the `ircOptions` object in the configuration file.

**Comment by ekmartin** [comment]
Hopefully this should be fixed with version 2.5.1 of discord-irc. Feel free to re-open if it's not!
