### ISSUE TITLE
PasteService for multiline messages?

### ISSUE THREAD

**Issue by ryantheleach** [reactiflux/discord-irc#355]
Would you guys accept a feature request to gist/pastebin/whatever long messages (especially code block formatted messages) to a gist service before sending to IRC to work together with the flood protection?

**Comment by ryantheleach** [comment]
> and in IRC this would have to be split up into many different messages and end up being quite spammy.

huh?

This is why I was suggesting using a gist/paste service in the first place?

**Comment by Throne3d** [comment]
Yes. I was agreeing.

**Comment by eXpl0it3r** [comment]
I'd like to see this added, as it's quite a bit of an issue, as Discord users are quite okay with posting a full sized code example, while on IRC it's unusable and casuses potential issues.

**Comment by ryantheleach** [comment]
@Phoenix616 I'd hope that isn't available to people unless they had joined the discord? regardless I don't see people using IRC firing up electron, joining the discord, just to view someone's paste.

**Comment by Phoenix616** [comment]
Afaik it's only available if you joined. Granted it's not as ideal as using an external paste service but it would solve the spam.

Also starting the webinterface doesn't take that long imo., not really ideal for people who don't want to use such a proprietary, centralised service but if they are in a channel that bridges it they already gift their data to that company so there's really no reason to not just make an account for that. (The better alternative would obviously be to stop using Discord instead of trying to cork around all of the issues with it.)

**Comment by Throne3d** [comment]
I'll close this in favor of #375, to track a more general "handle multi-line messages better" feature. (Note that we're not currently implementing new features, but if a simple, tested, and fully-ready PR drops on me, I might be convinced to merge it!)
