### ISSUE TITLE
Rejection/Deprecation Warnings

### ISSUE THREAD

**Issue by JoinedSenses** [reactiflux/discord-irc#356]
Howdy - I've returned with a new error message from this program.

Good news - the bots seem to continue to relay messages in two directions, working even after an error message was displayed.

Bad new, an error was displayed. Possible upstream issue, such as the previous one? The difference this time being that the program had run for ~4 days until an error was displayed. Previously, it would occur each time within 12 hours.

` (node:22828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: getaddrinfo EAI_AGAIN discordapp.com:443`  

`(node:22828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

`(node:22828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: getaddrinfo EAI_AGAIN discordapp.com:443 `

**Comment by Throne3d** [comment]
I'm not sure what's causing this issue. There seem to be a few problems that contain `UnhandledPromiseRejectionWarning`s. As I commented in another issue, it might be worth someone investigating the handler as described in this link: <https://www.bennadel.com/blog/3238-logging-and-debugging-unhandled-promise-rejections-in-node-js-v1-4-1-and-later.htm> (maybe merged into the regular code, even, with output in debug mode). It seems like this way we can get a proper traceback on the error, instead of having such limited information when the issues pop up.

**Comment by Throne3d** [comment]
I'll close this for now, as I haven't had further reports of it.
