### ISSUE TITLE
PM2 not recognizing errors

### ISSUE THREAD

**Issue by Kovaelin** [reactiflux/discord-irc#424]
I'm not sure if I should be asking here or over on @Unitech's page, but when the bot stops relaying (on the IRC, Discord, or both sides), PM2 doesn't seem to pick up on the error. Would anyone have any insight on why that is?

I'm running it by using `pm2 start discord-irc -- --config config.json`

Thanks.

**Comment by phit** [comment]
having the same issue, any advice would be really sweet!
thanks

**Comment by Throne3d** [comment]
It seems likely that this is because the bot doesn't go down (which is being tracked in other issues about the topic). Is this still a problem? If so, would you be able to run it with debug info added, as in <https://github.com/reactiflux/discord-irc/issues/328#issuecomment-518043890>, and get back to me, so I can solve the underlying cause?

**Comment by Throne3d** [comment]
Closing for lack of info. If it's still an issue, please get back in touch!
