### ISSUE TITLE
Foreign languages not showing properly

### ISSUE THREAD

**Issue by Tarlaref** [reactiflux/discord-irc#43]
I've been trying to use this for my community, but I cannot get Korean to display properly IRC -> Discord. Is there any possible way to solve it?

**Comment by ekmartin** [comment]
Can't seem to be able to reproduce this using version 0.6.1 of discord-irc:
![image](https://cloud.githubusercontent.com/assets/3536982/14245672/26631e7c-fa63-11e5-93b5-74041c1bf213.png)

Might have been fixed by upgrading to version 6.1.0 of discord.js. Could you try again using the latest version of discord-irc? Thanks!
