### ISSUE TITLE
Private Message Support

### ISSUE THREAD

**Issue by laxdragon** [reactiflux/discord-irc#458]
Basically, support for IRC /msg @ircuser so you can have a private chat between single users on Discord and IRC.

The ideal would be showing all discord users as individual accounts on the IRC server and that probably requires multiple IRC connections, one per Discord user. On the Discord side, I don't know if the API allows the bot to fake individual user connections.

But a backup would be to: /msg discordbot @ircuser <message content> from the IRC side. Not sure how you would initiate on the Discord side.

**Comment by mruno** [comment]
would like to see private messages from both IRC -> Discord and Discord -> IRC
Examples:

IRC -> Discord
- IRC_User private messages RelayBOT MESSAGE Discord_User Hello
- Result: RelayBot sends private message to Discord_User

Discord -> IRC
- Discord_User sends private message to RelayBot MESSAGE  IRC_User
- Result: RelayBot sends private message to IRC_User

**Comment by mono-ped** [comment]
As mruno said.

This would be great!

**Comment by Throne3d** [comment]
I'd expect this to be a huge pain if messaging IRC→Discord due to how people can have usernames and nicknames that collide a lot on Discord, and we don't currently expose these in much detail on the IRC side. There's also an issue Discord→IRC, in that the config allows for multiple IRC servers to be connected to the single bot user on Discord, and IRC nicknames won't be unique across servers.

We could maybe guess, or present some disambiguation method around this, but it seems like a real pain to get right (and private messages seem like they need to be implemented correctly), so this is looking pretty wishlisty.

**Comment by Throne3d** [comment]
Aha, this (or at least something similar) also came up before in #280, and it looks like we closed it then. Potentially a duplicate.

**Comment by Throne3d** [comment]
Closing this as out of scope for now! But if someone comes up with a simple, tested, fully-implemented solution for this (I think a pseudo-channel of "private message" might satisfy that?), I could look into merging an experimental feature for this!
