### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by Ryan526** [reactiflux/discord-irc#47]
Could you write a short guide on how to get this working on a fresh vps ? A quick step by step would be awesome.

**Comment by ekmartin** [comment]
Hi! I don't have time to write up an official guide right now, but here's a few tips:

1. Install Node.js (preferrably the latest version, using https://github.com/nodesource/distributions)
2. Install discord-irc, using `npm install -g discord-irc` (see [README](https://github.com/reactiflux/discord-irc#installation-and-usage)).
3. Create a Discord user that will serve as a bot.
4. Set up a config file, see the README for an [example](https://github.com/reactiflux/discord-irc#example-configuration) (note that you probably only need a minimal configuration, which is the first section of the example).
5. Install something that'll allow you to keep a process running forever, I prefer [supervisor](http://supervisord.org/).
6. Set up supervisor so that it runs `discord-irc --config /path/to/config`. For instructions on how to do this, check the supervisor docs: http://supervisord.org/running.html#adding-a-program
DigitalOcean's guide on how to set up supervisor can also come in handy:
https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps

Hope it helps, and feel free to ask if you get stuck along the way :)

**Comment by Ryan526** [comment]
Thank you! Will attempt setup sometime this week.

**Comment by Ryan526** [comment]
@ekmartin is it be possible to relay direct messages from a user on irc to a channel in discord instead of just linking two channels?

**Comment by ekmartin** [comment]
No, sorry, that's not possible.

**Comment by ekmartin** [comment]
You could make a locked IRC channel and just have that user in it though, which I guess would let you do much of the same?

**Comment by Ryan526** [comment]
@ekmartin
So basically this is whats up. There is a broadcast bot on IRC that is used to mass message people alerts. I want to be able to relay those messages to a #pings channel on my discord server so my users can get mobile push notifications. I can't change how anything works on the IRC side of it because it is outside of my control :(

**Comment by AdrienneLove** [comment]
@ryan526

I would recommend looking into discord.js and irc packages and maybe running your own bot if you need more than an echo between channels

**Comment by Kovaelin** [comment]
Is supervisord still the way to go? I'm having troube getting it to work. I've also been looking into [forever](https://github.com/foreverjs/forever).

**Comment by ekmartin** [comment]
@Kovaelin: if you have systemd (e.g. on Debian/Ubuntu) that's probably simpler. Here's a guide: http://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/
