### ISSUE TITLE
Feature Request: Make partial matching of discord users for mentions a toggleable option

### ISSUE THREAD

**Issue by ahalldin** [reactiflux/discord-irc#490]
Currently having an issue where other bots on our IRC channel are pinging users with similar names on our discord server, which is causing some of our users to be rather annoyed. I have solved the problem by commenting out the partial matching code present in bot.js, but it would be really nice if it was a toggleable option in the configuration instead.

**Comment by Throne3d** [comment]
Can you provide some examples of a message a bot might send and the expected & actual behavior? As far as I know, our mention matching is very similar to how Discord itself does it if you enter something in the client – so that, e.g., a message of `@Throne3dtest this is a message` will ping `@Throne3d` and have `test this is a message` after it, despite the lack of space. I might be missing something, though.

**Comment by Throne3d** [comment]
I'm going to close this for now, due to a lack of follow-up. If it's still happening, and you can demonstrate a way that our matching differs from Discord's interface, I'd be happy to reopen this issue!
