### ISSUE TITLE
Truncating long messages from Discord

### ISSUE THREAD

**Issue by freakuancy** [reactiflux/discord-irc#495]
The bot seems to truncate 5-15 characters at the end of each cut.

**Comment by Throne3d** [comment]
This seems like an issue with it calculating how much it can send in a single message (because it has to figure that out manually), but that's handled upstream.

Can I ask what IRC server you're on? Additionally, knowing the length of the nickname and host mask would be useful. It seems like this is calculated in a pretty hard-coded way, and I'd need to check what's going on more thoroughly to be able to fix it.

**Comment by Throne3d** [comment]
Closing this due to lack of follow-up.
