### ISSUE TITLE
IRC commands ("/") are sent as normal chat message? How?

### ISSUE THREAD

**Issue by x0rnn** [reactiflux/discord-irc#514]
In my config I have:

`"commandCharacters": ["/"]"`

so messages I send from Discord that start with "/", e.g.: "/msg name bla" should be sent on IRC without the username in front and registered as a normal IRC command (in this case the bot should message a user), instead, it's sent as a normal chat message on IRC, the "/" is escaped somehow:

```
[11:06] <@botname> Command sent from Discord by username:
[11:06] <@botname> /msg name bla
```

How is that even possible? What do I need to do so that gets recognized as a command on IRC and not normal chat?

**Comment by Throne3d** [comment]
Using IRC commands from the Discord side of things isn't supported – that's not what this functionality does. The `commandCharacters` option is designed to separate the prefix (e.g. `<Throne3d>`) from a message designed to trigger a bot, since bots tend to check messages by prefix. (That is, where an IRC message sent by Throne3d might trigger an IRC bot with `?test`, an IRC message sent by the bridge bot of `<Throne3d> ?test` won't, because it starts with the prefix, not with `?`.)

Supporting IRC commands in general would be awkward, and `/msg` in particular would need special handling to make sure it identifies who sent the message. I'm going to close this in favor of #458.
