### ISSUE TITLE
Update commander & discord.js

### ISSUE THREAD

**Issue by RhinosF1** [reactiflux/discord-irc#583]
"commander": "^7.0.0",
 "discord.js": "12.5.1",

are available.

The only issue I see is 
`1) CLI
       should be possible to give the config as an option:
     Error: Missing environment variable CONFIG_FILE
      at run (lib/cli.js:36:39)
      at Context.<anonymous> (test/cli.test.js:64:5)
      at processImmediate (node:internal/timers:464:21)`

**Comment by RhinosF1** [comment]
I did attempt this with #582 but I noticed package-lock.json changed the dependencies to use relative paths rather than the name and wasn't sure on that but feel free to restore if it's fine.

**Comment by Throne3d** [comment]
Hey there! The unrelated changes are probably due to a recent update in npm that uses a more modern package-lock.json. I'm not entirely sure when it's safe to upgrade this, especially since we still support Node 12, which I think doesn't support this format (whereas iirc Node 14 does).

I'll look into updating these dependencies! Thanks.

**Comment by Throne3d** [comment]
These are now available in the main branch (and so they're available on the Docker image and so on). I'll close this for now!
