### ISSUE TITLE
Support for Per Server Nicknames

### ISSUE THREAD

**Issue by smashedr** [reactiflux/discord-irc#63]
Discord has a new feature, that allows per server nicknames. When I set a server specific nickname, the bot still posts to IRC with my global nickname, not the nickname I had on the server that the bot is on.

**Comment by ekmartin** [comment]
I'm not completely sure I follow you, are you talking about the nickname that is used when the bot is posting to IRC? Because this is decided by the config field `nickname`, and doesn't have anything to do with the bot's username on the Discord side. 

https://github.com/reactiflux/discord-irc#example-configuration

**Comment by TheDoctorsLife** [comment]
I think he's referring to per server nicknames, as announced in this blog post. From the looks of it this would have to wait for discord.js to update with support before any work can go into this. https://blog.discordapp.com/2016-4-29-change-log/

**Comment by malleusinferni** [comment]
It looks like discord.js has nickname support as of 8.0 (see #78).

**Comment by alienth** [comment]
Support now exists, but discord-irc will have to have some changes to actually use the newly exposed info. API info is here: http://discordjs.readthedocs.io/en/indev/docs_server.html#detailsofuser-user

**Comment by devalnor** [comment]
+1

**Comment by omnicons** [comment]
+1
