### ISSUE TITLE
Bot seems to stop working randomly at some point

### ISSUE THREAD

**Issue by fletcher89** [reactiflux/discord-irc#73]
I'm running the bot on a Ubuntu 14.04 server using upstart.

At some point, the bot just seems to stop working. It does not crash at that point, it just stops sending messages. I'm also gonna try to figure out what's causing this myself, however I figured you might want to know.

I'm the third person of our discord/irc trying to run this and sooner or later we all ran into this issue.

**Comment by TheDoctorsLife** [comment]
How are you launching the bot?

**Comment by tjb0607** [comment]
I'm getting this as well, all that's happening is that the bot loses connection to discord, showing as offline in the discord user listing and not receiving any messages from the discord. The bot is still able to send messages from IRC to Discord, but not the other way around (because discord's API for sending messages doesn't require an active connection). I'm just launching the bot in the foreground with `discord-irc --config ~/.discord-irc/config`. I have to restart the bot every time this happens, so my screen session looks like [this](http://i.imgur.com/ImYFy2t.png).

**Comment by ZoeyCluff** [comment]
Currently dealing with this as well. I have to restart the bot several times a day. I'm launching with: 

discord-irc --config config.json

**Comment by tjb0607** [comment]
are you sure you're using the latest version? I was having this issue earlier but then [this commit](https://github.com/reactiflux/discord-irc/commit/b295e494b376df18e45fb480a951517869ef9051) fixed it

**Comment by ZoeyCluff** [comment]
I'm using whatever the latest is on NPM

**Comment by smashedr** [comment]
I have the same issue, but have been unable to what causes it, even with debugging output enabled. Most of the time, only the IRC side stops sending messages from Discord, and Discord side keeps posting messages from IRC.

The only thing I can think to do is run a cron job to restart the bot every day, since the problem always takes a couple days after a restart.

Bot is running like so:

[root@serv01 ~]# systemctl status smashed-gateway.service
● smashed-gateway.service - SmAsHeD Discord IRC Gateway
   Loaded: loaded (/etc/systemd/system/smashed-gateway.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2016-06-04 20:33:05 PDT; 2 weeks 4 days ago
 Main PID: 30809 (node)
   CGroup: /system.slice/smashed-gateway.service
           └─30809 node /bin/discord-irc --config /bot/discord-irc/smashed.json

**Comment by tjb0607** [comment]
does the bot show as offline in discord when this happens?

**Comment by smashedr** [comment]
I want to say it stays online, but I am not 100% sure. I will keep an eye on things and give a report on the next failure. (I am running 3 instances of this on one server).

[root@serv01 ~]# npm list -g | grep -i disco
├─┬ discord-irc@1.0.1
│ ├─┬ discord.js@8.0.0

**Comment by smashedr** [comment]
IRC --> Discord was still working fine. :+1:
Discord --> IRC Was tested at 18:48 did NOT work. :thumbsdown: 

But it seems me typing into Discord, triggered an error and restart (which afterwards worked):


[root@serv01 discord-irc]# systemctl status gosupvp-gateway.service -l
● gosupvp-gateway.service - Gosu PVP Discord IRC Gateway
   Loaded: loaded (/etc/systemd/system/gosupvp-gateway.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-06-29 18:48:32 PDT; 2min 51s ago
 Main PID: 2460 (node)
   CGroup: /system.slice/gosupvp-gateway.service
           └─2460 node /bin/discord-irc --config /bot/discord-irc/gosupvp.json

Jun 29 18:48:32 serv01.cssnr.com systemd[1]: Started Gosu PVP Discord IRC Gateway.
Jun 29 18:48:32 serv01.cssnr.com systemd[1]: Starting Gosu PVP Discord IRC Gateway...


[root@serv01 discord-irc]# journalctl -u gosupvp-gateway.service
-- Logs begin at Sat 2016-05-21 23:50:07 PDT, end at Wed 2016-06-29 18:51:02 PDT. --
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: /usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:932
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: if (!this.conn.requestedDisconnect) {
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: ^
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: TypeError: Cannot read property 'requestedDisconnect' of null
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: at Client.send (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:932:19)
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: at dequeue (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:962:22)
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: at wrapper [as _onTimeout] (timers.js:274:14)
Jun 29 18:48:31 serv01.cssnr.com discord-irc[3636]: at Timer.listOnTimeout (timers.js:119:15)
Jun 29 18:48:31 serv01.cssnr.com systemd[1]: gosupvp-gateway.service: main process exited, code=exited, status=1/FAILURE
Jun 29 18:48:31 serv01.cssnr.com systemd[1]: Unit gosupvp-gateway.service entered failed state.
Jun 29 18:48:31 serv01.cssnr.com systemd[1]: gosupvp-gateway.service failed.
Jun 29 18:48:32 serv01.cssnr.com systemd[1]: gosupvp-gateway.service holdoff time over, scheduling restart.
Jun 29 18:48:32 serv01.cssnr.com systemd[1]: Started Gosu PVP Discord IRC Gateway.
Jun 29 18:48:32 serv01.cssnr.com systemd[1]: Starting Gosu PVP Discord IRC Gateway...

**Comment by smashedr** [comment]
So it seems this is happening much more frequently. Since the upgrade to 1.0.3 while the IRC side of things stays connected, the Discord side can not send or receive messages and spams the logs with this error:

`info: Tried to send a message to a channel the bot isn't in`

This is happening quite frequently since the upgrade to 1.0.3 and I have had to install a cron job to restart all the gateways every hour to assure they do not stop working.

I will see if I can gather any debug logs.

**Comment by ekmartin** [comment]
discord-irc itself really doesn't do much fancy stuff in terms of talking to Discord, and everything it does happens through discord.js. Apparently version 9 of discord.js is a pretty substantial rewrite, which might fix some of these issues. If anyone wants to give upgrading it a try that'd be cool - wrote a bit about it here: https://github.com/reactiflux/discord-irc/issues/112#issuecomment-248488586

**Comment by ekmartin** [comment]
I've since upgraded discord-irc to the latest version of discord.js, so hopefully this should be better now. Let me know if it still persists and I'll reopen.

**Comment by Gamercord** [comment]
@ekmartin I am still experiencing this issue with my bot. It did fix it recently probably about the time you said you upgraded but now for the last week or so i have been having this issue where my bot does not respond at all in some channels but will respond in others.. Some servers are completely dead and others are working just fine
