### ISSUE TITLE
Kick people in IRC through discord?

### ISSUE THREAD

**Issue by siadevelopment** [reactiflux/discord-irc#74]
Is it possible to kick someone through discord that's in IRC? I've enabled command characters, however it's sending the ! or . along with the command. The bot has ops.

Thanks!

**Comment by ekmartin** [comment]
No, IRC commands like kick needs to be sent in the IRC protocol's format (see https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands), i.e. `KICK channel client message`. Normally when you write `/kick person` your IRC client translates that into the correct format, however with something like node-irc (which discord-irc uses) you'll have to send the commands yourself.

That would mean discord-irc would need some kind of command format (which can't be prefixed with /, since discord will think it's a command), like `!kick user` - which then would need to be translated into the correct IRC command. Who should be able to kick users? Should it be possible to do the same from IRC -> Discord?

And so on. I think the extra functionality needed overweights the feature here, sorry!
