### ISSUE TITLE
Discord tts not telling what user its from.

### ISSUE THREAD

**Issue by dmodoomsirius** [reactiflux/discord-irc#95]
Discord tts does not tell what user when relaying it is from. it says the bots name but not the irc nick its telling from.

**Comment by ekmartin** [comment]
@dmodoomsirius Sorry for the late answer! How are you getting the bot to send TTS messages in its current form? I made a few modifications in the tts branch for #135, but that was to make all messages be sent as TTS.

**Comment by dmodoomsirius** [comment]
@ekmartin its via Discords text to speech the bot isn't i was wondering if there was a way to have it say what user its being said from rather then the relay.

**Comment by ekmartin** [comment]
Ah, I see what you mean now. I don't think that's possible using Discord's APIs, but we're looking into changing the bot so it always uses the IRC user's nickname instead of the bot's. See #128 for status (when that's done it should have the behaviour you're expecting).

By the way, I didn't know that you could get Discord to read all messages using TTS, i.e. this setting: 
![image](https://cloud.githubusercontent.com/assets/3536982/19225430/a4cbfd7e-8e6a-11e6-9ff0-99c3f862c1a2.png)

Thanks!
